services:
  redis:
    image: redis
    container_name: redis
    env_file: ./.env
    restart: unless-stopped
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 250s
      retries: 60
  
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy 
    networks:
      - internal_network
      - public_network

  db:
    image: postgres:15
    container_name: postgresql
    env_file: ./.env
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - internal_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 250s
      retries: 60

  pgadmin:
    build: ./pgadmin
    container_name: pgadmin
    image: pgadmin
    env_file:
      - ./.env
    networks:
      - internal_network
      - public_network
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    entrypoint: ["/entrypoint_custom.sh"]

  web-back:
    build: ./backend
    entrypoint: ["/usr/src/app/entrypoint.sh"]
    container_name: backend
    image: backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/transcendence_back:/usr/src/app/transcendence_back/
      - migrations_data:/usr/src/app/transcendence_back/pong_back/migrations
    expose:
      - "8280"
    restart: unless-stopped
    networks:
      - internal_network
      - public_network
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=PRO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8280/ || exit 1"]
      interval: 5s
      timeout: 250s
      retries: 60

  prometheus:
    image: prom/prometheus:v2.45.6
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ./ssl/server.crt:/etc/prometheus/ssl/server.crt
      - ./ssl/server.key:/etc/prometheus/ssl/server.key
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
    ports:
      - '9090:9090'
    restart: unless-stopped
    networks:
      - internal_network
    depends_on:
      web-back:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "promtool", "check", "healthy", "--url", "http://localhost:9090"]
      interval: 5s
      timeout: 250s
      retries: 60
      start_period: 40s

  grafana:
    image: grafana/grafana:9.5.20
    container_name: grafana
    ports:
      - 3060:3000
    restart: unless-stopped
    networks:
      - internal_network
      - public_network
    env_file:
      - ./.env
    volumes:
      - ./grafana:/etc/grafana/provisioning
      - ./ssl/server.crt:/etc/grafana/ssl/server.crt
      - ./ssl/server.key:/etc/grafana/ssl/server.key
    depends_on:
      prometheus:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.14.2
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - ./elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
      - ./elasticsearch/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - ./elasticsearch/log:/usr/share/elasticsearch/logs/
      - ./ssl/elasticsearch.p12:/usr/share/elasticsearch/config/elasticsearch.p12
    env_file:
      - ./.env
    environment:
      - xpack.security.enabled=true
      - ELASTICSEARCH_DEFAULT=${ELASTICSEARCH_DEFAULT}
      - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_USER=${KIBANA_USER}
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - internal_network
      - public_network
    healthcheck:
      test: ["CMD-SHELL", "curl -u ${ELASTICSEARCH_DEFAULT}:${ELASTICSEARCH_PASSWORD} -k -f https://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 250s
      retries: 60

  elasticsetup:
    image: alpine/curl:8.8.0
    container_name: elasticsetup
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_DEFAULT=${ELASTICSEARCH_DEFAULT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_USER=${KIBANA_USER}
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "/usr/share/elasticsearch/config/setup.sh"]
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/config/
    networks:
      - internal_network

  logstash:
    container_name: logstash
    image: logstash:8.14.2
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
      - ./ssl/server.crt:/usr/share/logstash/config/server.crt
      - ./ssl/server.key:/usr/share/logstash/config/server.key
    command: logstash -f /usr/share/logstash/config/logstash.conf
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_DEFAULT=${ELASTICSEARCH_DEFAULT}
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - "5959:5959"
      - "9600:9600"
    restart: unless-stopped
    networks:
      - internal_network
    depends_on:
      elasticsetup:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9600/_node/stats || exit 1"]
      interval: 5s
      timeout: 275s
      retries: 65
      start_period: 60s

  kibana:
    image: kibana:8.14.2
    container_name: kibana
    ports:
      - "5601:5601"
    restart: unless-stopped
    networks:
      - internal_network
      - public_network
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./ssl/server.crt:/usr/share/kibana/config/server.crt
      - ./ssl/server.key:/usr/share/kibana/config/server.key
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_DEFAULT=${ELASTICSEARCH_DEFAULT}
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    depends_on:
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:5601 || exit 1"]
      interval: 5s
      timeout: 275s
      retries: 65
      start_period: 60s

  kibanasetup:
    image: alpine/curl:8.8.0
    container_name: kibanasetup
    env_file:
      - ./.env
    environment:
      - ELASTICSEARCH_DEFAULT=${ELASTICSEARCH_DEFAULT}
      - ELASTIC_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - KIBANA_USER=${KIBANA_USER}
    depends_on:
      kibana:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "/usr/share/kibana/config/init_kibana.sh"]
    volumes:
      - ./kibana/init_kibana.sh:/usr/share/kibana/config/init_kibana.sh
      - ./kibana/visualization:/usr/share/kibana/visualization
    networks:
      - internal_network

  web-front:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    image: frontend
    depends_on:
      web-back:
        condition: service_healthy
    volumes:
      - ./frontend/transcendence_front:/usr/src/app/transcendence_front/
    ports:
      - 4200:4200
    networks:
      - public_network
    env_file:
      - ./.env
  
  apache-back:
    build: ./apache_back
    container_name: apacheback
    image: apacheback
    env_file:
      - ./.env
    networks:
      - internal_network
      - public_network
    volumes:
      - ./ssl:/etc/apache2/ssl
    ports:
      - 8443:443
    depends_on:
      web-back:
        condition: service_healthy

  apache-front:
    build: ./apache_front
    container_name: apache_front
    image: apache_front
    env_file:
      - ./.env
    networks:
      - public_network
    volumes:
      - ./frontend/transcendence_front/dist:/var/www/html/
      - ./ssl:/usr/local/share/ca-certificates
      - ./ssl:/etc/apache2/ssl
    ports:
      - 4280:80
      - 42443:443

networks:
  internal_network:
    driver: bridge
    internal: true
  public_network:
    driver: bridge

volumes:
  db_data:
    name: ft_transcendence_db_data
    driver: local

  migrations_data:
    name: ft_transcendence_migrations_data
    driver: local

  front_cache:
    name: ft_transcendence_front_cache
    driver: local

  redisinsight_data:
    name: ft_transcendence_redisinsight_data
    driver: local

  elasticsearch_data:
    name: ft_transcendence_elasticsearch_data
    driver: local
